[theme]
base = "light"
primaryColor = "#0EA5E9"
backgroundColor = "#F8FAFC"
secondaryBackgroundColor = "#EFF6FF"
textColor = "#0F172A"
font = "sans serif"

[server]
maxUploadSize = 50
enableCORS = false
enableXsrfProtection = true
headless = true

[browser]
gatherUsageStats = false

[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true

[logger]
level = "info"
